Build/testing-docker/docker-compose.yml
Testing against core v12 has been done with testing-framework main.
This is now changed so core v12 also uses typo3/testing-framework 7
to act as multi-core testing with the compatibility version.
=> [TASK] Use typo3/testing-framework 7 for core v11 and v12 testing

.github/workflows/testscorev11.yml, Build/FunctionalTests.xml, Classes/Health/InlineForeignFieldChildrenParentDeleted.php, Classes/Health/InlineForeignFieldChildrenParentLanguageDifferent.php, Classes/Health/InlineForeignFieldChildrenParentMissing.php
Fix a possible PHP 8 related array access warning when
inline children point to not existing TCA parent tables.
Fix functional test setup to not suppress warnings
to let tests fail properly.
Also disable functional core v11, postgres, PHP 8.2 testing
since it triggers a doctrine 2.13.9 deprecation.
Closes: #15
=> [BUGFIX] PHP warning inline children point to invalid TCA table

Build/testing-docker/docker-compose.yml, composer.json
This changes requires the intermediate workaround composer plugin `sbuerk/typo3-cmscomposerinstallers-testingframework-bridge` to mitigate testing issues against TYPO3v12.
This only solves the generic composer installation for now. Sadly, due another change in core which removed database column from `sys_file_reference`, dbdoctor checks and corresponding tests are failing now due not existing table column.
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75916
=> [TASK] Ensure core v12 testing works

.github/workflows/publish.yml, .github/workflows/testscorev11.yml, .github/workflows/testscorev12.yml
GitHub has deprecated node v12 support for executing GitHub actions. This currently adds corresponding deprecation note to action results, also not failing for now.
This change updates action/checkout to use v3 instead of v2 to use Node v16 compatible version and thus avoiding the deprecation notice.
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> [TASK] Upgrade action/checkout to avoid deprecation message

Classes/Health/PagesTranslatedLanguageParentDifferentPid.php
Fix for PHP Warning "undefined array key" when throwing exception in PagesTranslatedLanguageParentDifferentPid.
Resolves: #27
=> [BUGFIX] Fix undefined array key

Build/testing-docker/docker-compose.yml, composer.json
The now obsolete "sbuerk/typo3-cmscomposerinstallers-testingframework-bridge"
is removed again and necessary configuration changes applied.
=> [TASK] Avoid typo3/cms-composer-installers workaround composer plugin

Classes/Commands/HealthCommand.php, Classes/DatabaseSchema/DatabaseSchemaChecker.php
dbdoctor relies on DB table/fields being in
sync with TCA.
Use the SchemaMigrator to check for incomplete
DB schema before starting with health checks.
Resolves: #14
=> [FEATURE] Check TCA<->DB schema integrity

Classes/Commands/HealthCommand.php, README.md
This should harden the "-m execute" option
a bit further.
Resolves: #40
=> [TASK] Require valid -f option with -m execute

Classes/HealthCheck/AbstractHealthCheck.php
To scroll less, it is helpful to output the
header summary each time when intaracting
with "p" and "d".
=> [TASK] Render output summary with "p" and "d" again

Build/Scripts/runTests.sh
Minor change in runTests.sh to allow a test
file as argument and let phpunit find it
properly again.
=> [BUGFIX] Allow running single test again

Classes/HealthCheck/AbstractHealthCheck.php
Current "update" health checks may need to
delete records instead, when they are
within workspaces. The change adapts
the "help" wording accordingly.
=> [TASK] Lift hard distinction between delete and update

Classes/HealthCheck/AbstractHealthCheck.php, Classes/HealthCheck/InlineForeignFieldChildrenParentDeleted.php, Classes/HealthCheck/InlineForeignFieldChildrenParentLanguageDifferent.php, Classes/HealthCheck/InlineForeignFieldChildrenParentMissing.php, Classes/HealthCheck/SysFileReferenceInvalidFieldname.php, Classes/HealthCheck/TcaTablesDeleteFlagZeroOrOne.php, Classes/HealthCheck/TcaTablesInvalidLanguageParent.php, Classes/HealthCheck/TcaTablesPidDeleted.php, Classes/HealthCheck/TcaTablesPidMissing.php, Classes/HealthCheck/TcaTablesTranslatedLanguageParentDeleted.php, Classes/HealthCheck/TcaTablesTranslatedLanguageParentDifferentPid.php, Classes/HealthCheck/TcaTablesTranslatedLanguageParentMissing.php, Classes/HealthCheck/TcaTablesTranslatedParentInvalidPointer.php, Classes/HealthCheck/WorkspacesNotLoadedRecordsDangling.php, Classes/HealthCheck/WorkspacesRecordsOfDeletedWorkspaces.php, Classes/HealthCheck/WorkspacesSoftDeletedRecords.php, Classes/Helper/TcaHelper.php, Configuration/Services.yaml, README.md
TCA is considered static during dbdoctor execution. Inject TcaHelper to AbstractHealthCheck, and mark
it a shared service. No need to make it public, either.
=> [TASK] TcaHelper is a stateless service

Classes/HealthCheck/AbstractHealthCheck.php, Classes/HealthCheck/InlineForeignFieldChildrenParentDeleted.php, Classes/HealthCheck/InlineForeignFieldChildrenParentLanguageDifferent.php, Classes/HealthCheck/InlineForeignFieldChildrenParentMissing.php, Classes/HealthCheck/PagesBrokenTree.php, Classes/HealthCheck/PagesTranslatedLanguageParentDeleted.php, Classes/HealthCheck/PagesTranslatedLanguageParentDifferentPid.php, Classes/HealthCheck/PagesTranslatedLanguageParentMissing.php, Classes/HealthCheck/SysFileReferenceDangling.php, Classes/HealthCheck/SysFileReferenceInvalidPid.php, Classes/HealthCheck/SysFileReferenceInvalidTableLocal.php, Classes/HealthCheck/SysFileReferenceLocalizedFieldSync.php, Classes/HealthCheck/SysFileReferenceLocalizedParentDeleted.php, Classes/HealthCheck/SysFileReferenceLocalizedParentExists.php, Classes/HealthCheck/TcaTablesDeleteFlagZeroOrOne.php, Classes/HealthCheck/TcaTablesPidDeleted.php, Classes/HealthCheck/TcaTablesPidMissing.php, Classes/HealthCheck/TcaTablesTranslatedLanguageParentDeleted.php, Classes/HealthCheck/TcaTablesTranslatedLanguageParentDifferentPid.php, Classes/HealthCheck/TcaTablesTranslatedLanguageParentMissing.php, Classes/HealthCheck/TcaTablesTranslatedParentInvalidPointer.php, Classes/HealthCheck/WorkspacesNotLoadedRecordsDangling.php, Classes/HealthCheck/WorkspacesRecordsOfDeletedWorkspaces.php, Classes/HealthCheck/WorkspacesSoftDeletedRecords.php, Classes/HealthFactory/HealthFactory.php
Single checks now output general "tags"
to declare their possible changes.
The imprecise [DELETE] and [UPDATE]
declaration is removed in favor of
these tags.
=> [TASK] Improve output and wording

Classes/HealthCheck/TcaTablesTranslatedLanguageParentDifferentPid.php
This is a quick-fix for #30: Exclude the table
in TcaTablesTranslatedLanguageParentDifferentPid
to not trigger loops.
A real fix needs more investigation and probably
a check to change parent records, first.
Related: #30
=> [BUGFIX] Exclude sys_file_reference in a check

Classes/HealthCheck/TcaTablesLanguageLessThanOneHasZeroLanguageSource.php, Classes/HealthFactory/HealthFactory.php, Classes/Helper/TcaHelper.php, Classes/Renderer/RecordsRenderer.php, Tests/Unit/Helper/TcaHelperTest.php
A first check to deal with l10n_source: Rows with
sys_language_uid = 0 or -1 must have l10n_source
set to zero. This is added pretty early to not confuse other checks.
=> [FEATURE] sys_language_uid <= 0 rows have l10n_source=0

Classes/HealthCheck/SysFileReferenceLocalizedFieldSync.php, Classes/HealthCheck/SysFileReferenceLocalizedParentExists.php, Classes/HealthFactory/HealthFactory.php
The SysFileReferenceDangling check is "safe" and
should be done before the localization checks
are done to potentially reduce findings of those
already.
=> [TASK] First SysFileReferenceDangling more early

Classes/HealthCheck/AbstractHealthCheck.php, Classes/HealthCheck/SysFileReferenceLocalizedParentExists.php
That check is risky since it may lead to changed
FE output (BE usually excepts when editing).
Explain the situation accordingly and have a new
"risky" flag to make this more obvious. Outline
a possible mitigation in an @todo as well.
=> [TASK] SysFileReferenceLocalizedParentExists is risky

Classes/HealthCheck/SysFileReferenceLocalizedParentDeleted.php, Classes/HealthCheck/SysFileReferenceLocalizedParentExists.php
Similar to SysFileReferenceLocalizedParentExists,
this check is marked risky with a similar exlpanation.
=> [TASK] SysFileReferenceLocalizedParentDeleted is risky

Classes/HealthCheck/SysFileReferenceLocalizedFieldSync.php
This is about sys_file_reference "images" again.
Depending on the inline parent record, this
may potentially change FE output.
=> [TASK] SysFileReferenceLocalizedFieldSync is risky

Classes/HealthCheck/TcaTablesPidMissing.php, Classes/HealthCheck/TtContentPidMissing.php, Classes/HealthFactory/HealthFactory.php, Tests/Functional/Fixtures/TcaTablesPidMissingImport.csv, Tests/Functional/Fixtures/TtContentPidMissingFixed.csv, Tests/Functional/Fixtures/TtContentPidMissingImport.csv, Tests/Functional/HealthCheck/TtContentPidMissingTest.php
tt_content plays an important role and we need some earlier checks to make sure things fit. The patch
extracts 'tt_content' from the later check
TcaTablesPidMissing to an earlier point.
=> [TASK] Have basic check for tt_content on existing pid early

Classes/HealthCheck/TtContentDeletedLocalizedParentExists.php, Classes/HealthCheck/TtContentPidDeleted.php, Classes/HealthFactory/HealthFactory.php, Tests/Functional/Fixtures/TtContentDeletedLocalizedParentExistsFixed.csv, Tests/Functional/Fixtures/TtContentDeletedLocalizedParentExistsImport.csv, Tests/Functional/HealthCheck/TtContentDeletedLocalizedParentExistsTest.php
Similar to an existing sys_file_reference check, this one is earlier and dedicated to tt_content.
=> [FEATURE] Remove deleted localized tt_content records without parent

Classes/Renderer/RecordsRenderer.php
The RecordRenderer tends to throw exceptions when
sys_workspace table does not exist. Improve sanitation.
=> [BUGFIX] RecordRenderer handles missing sys_workspace table

.github/workflows/testscorev12.yml, Build/Scripts/runTests.sh, composer.json
- **[TASK] Add `typo3/cms-install` as dev dependency**
The `setup` command is part of `EXT:install` and
required to setup instances, for example for the
`cli` phpt based testsuite.
This system extension is kind of optional and no
longer installed by default in composer instances,
but literally needed when the setup command should
be used to setup instances. Add it as development
dependency !
```shell
composer req --dev --no-update \
"typo3/cms-install":"^12.4 || ^13.4"
```
- **[TASK] Setup cli test instances providing all setup command arguments**
- **[TASK] Enable GitHub action tests for the cli testsuite**
=> [TASK] Ensure correct setup for cli tests

Classes/DatabaseSchema/DatabaseSchemaChecker.php, Tests/Functional/DatabaseSchema/DatabaseSchemaCheckerTest.php
Doctrine DBAL 4 made class properties private in most
classes, declaring them as internal api and has been
enforced with TYPO3 v13 due to the upgrade to that
version.
This change replaces property access on doctrine dbal
classes in `DatabaseSchemaChecker` with the suiting
getter method to be compatible with both TYPO3 and
Doctrine DBAL versions.
Testing `DatabaseSchemaChecker` now to cover these
API calls.
=> [BUGFIX] Use getter instead of accessing doctrine class properties

Build/Scripts/runTests.sh
8.1 forces core v12 and ignores -t 13 argument.
Use PHP 8.2 by default to not mix this up easily.
=> [TASK] Use PHP 8.2 by default in runTests.sh

Build/phpstan-baseline.neon, Classes/HealthCheck/PagesBrokenTree.php, Classes/Helper/PagesRootlineHelper.php, Tests/Functional/Fixtures/PagesBrokenTreeImport.csv, Tests/Functional/Helper/PagesRootlineHelperTest.php
Implement handling for pages that pid-point to each other and thus form an invalid loop. This also speeds up "PagesBrokenTree" quite a bit since it needs no full rootline check with DB queries for each page
anymore.
Resolves: #110
=> [BUGFIX] Deal with broken pages loops

Classes/HealthCheck/PagesTranslatedLanguageParentSelf.php, Classes/HealthCheck/TcaTablesPidDeleted.php, Classes/HealthCheck/TcaTablesTranslatedParentInvalidPointer.php, Classes/HealthCheck/TcaTablesTranslatedParentSelf.php, Classes/HealthFactory/HealthFactory.php, Classes/Renderer/AffectedPagesRenderer.php, Classes/Renderer/RecordsRenderer.php, README.md, Tests/Cli/InvalidArgumentTest.phpt, Tests/Functional/Fixtures/PagesTranslatedLanguageParentSelfFixed.csv, Tests/Functional/Fixtures/PagesTranslatedLanguageParentSelfImport.csv, Tests/Functional/Fixtures/TcaTablesTranslatedParentInvalidPointerFixed.csv, Tests/Functional/Fixtures/TcaTablesTranslatedParentInvalidPointerImport.csv, Tests/Functional/Fixtures/TcaTablesTranslatedParentSelfFixed.csv, Tests/Functional/Fixtures/TcaTablesTranslatedParentSelfImport.csv, Tests/Functional/HealthCheck/PagesTranslatedLanguageParentSelfTest.php, Tests/Functional/HealthCheck/TcaTablesTranslatedParentSelfTest.php
TcaTablesTranslatedParentInvalidPointer stumbles when it encounters a records having "transOrigPointerField" (l10n_parent) set to its own uid. It also stumbles when an l10n_parent of a different row points to such a record.
To fix this, two new checks are added: Scan for such records in pages and set them deleted, then scan for such records in all other tables and set them deleted.
Additionally, sanitize TcaTablesTranslatedParentInvalidPointer to skip such records which may happen if the check has to run multiple times in one run because it follows a chain.
=> [BUGFIX] Handle records having l10n_parent = uid
