.github/workflows/testscorev11.yml
.github/workflows/testscorev12.yml
Build/Scripts/runTests.sh
Build/testing-docker/docker-compose.yml

[TASK] Add PHP 8.2 to test matrix

---

Classes/Health/AbstractHealth.php

When checks change database and -f option is used,
the dumped sql file now contains the class name that
triggered this change.

[FEATURE] Comment which check triggered a statement to sql

---

Classes/Health/HealthFactory.php
Classes/Health/InlineForeignFieldChildrenParentMissing.php
Classes/Helper/TcaHelper.php
Tests/Functional/Fixtures/InlineForeignFieldChildrenParentMissingTestFixed.csv
Tests/Functional/Fixtures/InlineForeignFieldChildrenParentMissingTestImport.csv
Tests/Functional/Health/InlineForeignFieldChildrenParentMissingTest.php
Tests/Unit/Helper/TcaHelperTest.php

[FEATURE] Find inline children pointing to not existing parents

---

Classes/Commands/HealthCommand.php

[FEATURE] Remind refindex update when dbdoctor changed something

---

Build/php-cs-fixer/config.php
Build/testing-docker/docker-compose.yml
Configuration/Services.php
composer.json

[TASK] Avoid typo3/coding-standards

---

Classes/HealthCheck/TcaTablesDeleteFlagZeroOrOne.php
Classes/HealthFactory/HealthFactory.php
Classes/Helper/TcaHelper.php
README.md
Tests/Functional/Fixtures/TcaTablesDeleteFlagZeroOrOneFixed.csv
Tests/Functional/Fixtures/TcaTablesDeleteFlagZeroOrOneImport.csv
Tests/Functional/HealthCheck/TcaTablesDeleteFlagZeroOrOneTest.php
Tests/Unit/Helper/TcaHelperTest.php

A pretty early health check to verify TCA
soft-delete column rows values are either
zero or one.
Resolves: #32

[FEATURE] Ensure "deleted" is either 0 or 1

---

Classes/HealthCheck/AbstractHealthCheck.php
Classes/HealthCheck/InlineForeignFieldChildrenParentMissing.php
Classes/HealthCheck/PagesBrokenTree.php
Classes/HealthCheck/PagesTranslatedLanguageParentDifferentPid.php
Classes/HealthCheck/PagesTranslatedLanguageParentMissing.php
Classes/HealthCheck/SysFileReferenceDangling.php
Classes/HealthCheck/SysFileReferenceInvalidFieldname.php
Classes/HealthCheck/SysFileReferenceInvalidTableLocal.php
Classes/HealthCheck/SysFileReferenceLocalizedParentExists.php
Classes/HealthCheck/TcaTablesDeleteFlagZeroOrOne.php
Classes/HealthCheck/TcaTablesInvalidLanguageParent.php
Classes/HealthCheck/TcaTablesPidMissing.php
Classes/HealthCheck/TcaTablesTranslatedLanguageParentMissing.php
Classes/HealthCheck/WorkspacesNotLoadedRecordsDangling.php
Classes/HealthCheck/WorkspacesRecordsOfDeletedWorkspaces.php
Classes/HealthCheck/WorkspacesSoftDeletedRecords.php

Rename and refactor some methods of AbstractHealthCheck to make delete<->update record API more consistent.

[TASK] Streamline delete/update API

---

Classes/HealthCheck/AbstractHealthCheck.php
Classes/HealthCheck/InlineForeignFieldChildrenParentDeleted.php
Classes/HealthCheck/InlineForeignFieldChildrenParentMissing.php
Classes/HealthCheck/PagesTranslatedLanguageParentDeleted.php
Classes/HealthCheck/SysFileReferenceLocalizedFieldSync.php
Classes/HealthCheck/SysFileReferenceLocalizedParentDeleted.php
Classes/HealthCheck/TcaTablesInvalidLanguageParent.php
Classes/HealthCheck/TcaTablesPidDeleted.php
Classes/HealthCheck/TcaTablesPidMissing.php
Classes/HealthCheck/TcaTablesTranslatedLanguageParentDeleted.php
Classes/HealthCheck/TcaTablesTranslatedLanguageParentMissing.php
Classes/HealthCheck/WorkspacesNotLoadedRecordsDangling.php
Classes/HealthCheck/WorkspacesRecordsOfDeletedWorkspaces.php
Classes/HealthCheck/WorkspacesSoftDeletedRecords.php

Implement softOrHardDeleteRecords() and
deleteTcaRecords() as additional helpers
to make API a bit more convenient.

[TASK] More AbstractHealthCheck helper methods

---

Classes/HealthCheck/WorkspacesPidNegative.php
Classes/HealthFactory/HealthFactory.php

[FEATURE] Remove pid=-1 records

---

Classes/HealthCheck/AbstractHealthCheck.php
Classes/HealthCheck/SysFileReferenceInvalidPid.php
Classes/HealthCheck/TcaTablesTranslatedLanguageParentDifferentPid.php
Classes/HealthCheck/WorkspacesT3verStateNotZeroInLive.php

Have some helper methods to not repeat
output creation at various places.

[TASK] DRY per-table output

---

Classes/HealthCheck/TcaTablesPidDeleted.php
Classes/HealthCheck/TtContentPidDeleted.php
Classes/HealthFactory/HealthFactory.php
Tests/Functional/Fixtures/TcaTablesPidDeletedFixed.csv
Tests/Functional/Fixtures/TcaTablesPidDeletedImport.csv
Tests/Functional/Fixtures/TtContentPidDeletedFixed.csv
Tests/Functional/Fixtures/TtContentPidDeletedImport.csv
Tests/Functional/HealthCheck/TtContentPidDeletedTest.php

Similar to TcaTablesPidMissing.

[TASK] Have basic check for tt_content on deleted pid early

---

Classes/HealthCheck/TtContentLocalizedDuplicates.php
Classes/HealthFactory/HealthFactory.php
Tests/Functional/Fixtures/TtContentLocalizedDuplicatesFixed.csv
Tests/Functional/Fixtures/TtContentLocalizedDuplicatesImport.csv
Tests/Functional/HealthCheck/TtContentLocalizedDuplicatesTest.php

[FEATURE] Fix duplicated localized tt_content records

---

Classes/HealthCheck/AbstractHealthCheck.php
Classes/HealthCheck/InlineForeignFieldChildrenParentLanguageDifferent.php
Classes/HealthCheck/SysRedirectInvalidPid.php
Classes/HealthCheck/TcaTablesTranslatedLanguageParentDifferentPid.php
Classes/HealthCheck/TtContentLocalizationSourceExists.php
Classes/HealthCheck/TtContentLocalizationSourceLogicWithParent.php
Classes/HealthCheck/TtContentLocalizationSourceSetWithParent.php
Classes/HealthCheck/TtContentLocalizedParentDifferentPid.php
Classes/HealthCheck/WorkspacesT3verStateNotZeroInLive.php
Classes/Renderer/AffectedPagesRenderer.php
composer.json

> composer req --dev friendsofphp/php-cs-fixer:^3.37.1
> Build/Scripts/runTests.sh -p 8.1 -s cgl

[TASK] Bump friendsofphp/php-cs-fixer:^3.37.1

---

.github/workflows/publish.yml
.github/workflows/testscorev11.yml
.github/workflows/testscorev12.yml

[TASK] Avoid GH workflow deprecations

---

README.md

[TASK] Update README.md on record update/delete strats

---

Build/php-cs-fixer/config.php
Tests/Functional/HealthCheck/TtContentDeletedLocalizedParentDifferentPidTest.php
composer.json

Avoid deprecated rules and update a finding.
> composer req --dev friendsofphp/php-cs-fixer:^3.52.0

[TASK] Require friendsofphp/php-cs-fixer:^3.52.0

---

composer.json

> composer req --dev bnf/phpstan-psr-container:^1.1
> composer req --dev friendsofphp/php-cs-fixer:^3.68.5
> composer req --dev phpstan/phpstan:^1.12.18
> composer req --dev phpstan/phpstan-phpunit:^1.4.2
> composer req --dev typo3/testing-framework:^7.1.1

[TASK] Raise some dev dependencies

---

composer.json
ext_emconf.php

Also update branch alias and ext_emconf.php
> composer req php:^8.1
> composer req typo3/cms-core:"^12.4 || ^13.4"
> composer req --dev typo3/cms-impexp:"^12.4 || ^13.4"
> composer req --dev typo3/cms-redirects:"^12.4 || ^13.4"
> composer req --dev typo3/cms-workspaces:"^12.4 || ^13.4"

[TASK] Update requirements to core v12/v13

---

.github/workflows/testscorev12.yml
Build/FunctionalTests.xml
Build/Scripts/runTests.sh
Build/UnitTests.xml
Tests/Unit/Helper/TcaHelperTest.php
composer.json

> composer req --dev phpunit/phpunit:"^10 || ^11"
> composer req --dev typo3/testing-framework:^8.2.7

[TASK] Update dev dependencies

---

Build/phpstan.neon
composer.json

Similar to what core did.
> composer rem --dev friendsoftypo3/phpstan-typo3

[TASK] Avoid friendsoftypo3/phpstan-typo3

---

Build/Scripts/runTests.sh

[BUGFIX] runTests.sh do not allow -p 8.1 with -t 13

---

ext_emconf.php

According to `composer.json` it's "^12.4 || ^13.4".

[BUGFIX] Set correct TYPO3-requirement

---

Classes/Renderer/RecordsRenderer.php

TCA tables that are localization aware but not soft-delete aware can crash RecordsRenderer ("d" in interactive mode).
Sanitize this case.
Thanks to Achim Fritz for pointing this out.

[BUGFIX] Avoid RecordsRenderer crash

---

composer.json

> composer req --dev phpunit/phpunit:"^10.5.47 || ^11.5.26 || ^12.2.6"

[TASK] Allow phpunit v12

---

composer.json

> composer req --dev friendsofphp/php-cs-fixer:^3.82.2 \
phpstan/phpstan:^2.1.17 \
phpstan/phpstan-phpunit:^2.0.6

[TASK] Update dev tools
